### PR TITLE
CI test

### PR DESCRIPTION
**Pull request by nspark**

### CODE REVIEW

**Comment by nspark** [comment]
This is a REST comment.

**Comment by nspark** [comment]
Another RESTful comment

**Comment by nspark** [comment]
[Draft PDF of this PR for commit f7c24d3](https://www.dropbox.com/s/55tww76k9c8rbzm/openshmem-draft-f7c24d3.pdf?dl=0)

**Comment by nspark** [comment]
[Draft PDF of this PR for commit c0cffd6](https://www.dropbox.com/s/8nd1keuu12j7b7a/openshmem-draft-c0cffd6.pdf)

**Comment by ghost** [comment]
[Draft PDF of this PR for commit 25e74eb](https://www.dropbox.com/s/5xdeux84lk6tmi3/openshmem-draft-25e74eb.pdf?dl=1)

**Comment by nspark** [comment]
TODO: Fix the commit reference in the comment URL. It doesn't match the commit hash on the PR.

**Comment by ghost** [comment]
[Draft PDF of this PR for commit 47d6967](https://www.dropbox.com/s/0uxkgyfgrqc5n9l/openshmem-draft-47d6967.pdf?dl=1)

**Comment by ghost** [comment]
[Draft PDF of this PR for commit 034956c](https://www.dropbox.com/s/jqnxps35gsu41uf/openshmem-draft-034956c.pdf?dl=1)

**Comment by ghost** [comment]
[Draft PDF of this PR for commit 7800dd4](https://www.dropbox.com/s/ju7wlzfvijljgn1/openshmem-draft-7800dd4.pdf?dl=1)

**Comment by ghost** [comment]
[Draft PDF of this PR for commit 065590c](https://www.dropbox.com/s/pn197dn24epq37z/openshmem-draft-065590c.pdf?dl=1)

**Comment by ghost** [comment]
[Draft PDF of this PR as of commit `3b5cc3e`](https://www.dropbox.com/s/q7lajqxugkfb2s7/openshmem-draft-3b5cc3e.pdf?dl=1)

**Comment by ghost** [comment]
Alert @nspark; the OpenSHMEM bot failed

**Comment by ghost** [comment]
[Draft PDF of this PR as of commit `5991bca`](https://www.dropbox.com/s/brxx0l2z8a78vh6/openshmem-draft-5991bca.pdf?dl=1)

**Comment by ghost** [comment]
[Draft PDF of this PR as of commit `7e14bb3`](https://www.dropbox.com/s/9l6pr2wavhlrnd9/openshmem-draft-7e14bb3.pdf?dl=1)

**Comment by ghost** [comment]
[Draft PDF of this PR as of commit `ab85d2e`](https://www.dropbox.com/s/q888wbb0aizfvwq/openshmem-draft-ab85d2e.pdf?dl=1)

**Comment by ghost** [comment]
[Draft PDF of this PR as of commit `b85766c`](https://www.dropbox.com/s/9yr5n0y84way4n8/openshmem-draft-b85766c.pdf?dl=1)

**Pull request closed without merging**
