### PR TITLE
Section/rma amo/consist params

### PR DESCRIPTION
**Pull request by minsii**
This PR tries to fix two consistency issues in the RMA/AMO sections.
1. IN/OUT attribution.
2. Argument naming for dest/source objects.

### CODE REVIEW

**Comment by minsii** [comment]
@nspark : Could you please review the patches and merge them into the section PR ?

**Comment by nspark** [comment]
@min-si I'm not sure that I see how your commit comment for ad22ac5 (quoted below) is actually consistent with your changes, specifically with respect to "OUT" variables.

>The change follows two rules:
>- In all remote write routines (e.g., put, atomic_inc), the updated remote date object is marked as IN.
>- In all fetch routines (e.g., get, atomic_fetch_inc), the updated local data object is marked as OUT.

For example, `shmem_atomic_fetch_inc` is *not* changed by this PR -- although `shmem_atomic_fetch_{add,and,or,xor}` are -- and the `dest` argument for all of them is marked as IN.

I don't disagree that the specification is inconsistent; I just want to make sure that whatever we decide should be the consistent approach matches the rationale behind it.

**Comment by nspark** [comment]
@min-si I'm happy to resolve the conflicts myself, but I am concerned some of this will be contentious. In particular, changing the `dest` argument for the put family of RMA operations to "IN".

**Comment by nspark** [comment]
In general, I think the whole IN/OUT distinction is superfluous (at best) and confusing (at worst). C already has a way of expressing the contract that a function shall not change the object pointed to by a pointer-type argument; it's called `const`. I'd love to see them removed entirely from the specification, but that will need to wait for a 1.5 issue.

I think there are three models for these sorts of "modes", as could be used by OpenSHMEM.

Specifically, a non-`const` pointer argument to a function call has a mode of:

When the object pointed to by the argument... | Model 1 | Model 2 | Model 3 | Example
----- | ------ | ------ | ------ | ------
...will only be modified if the target PE is the calling PE | IN | IN/OUT | OUT | `dest` of `shmem_put`
...is unconditionally modified by the call | OUT | OUT | OUT | `dest` of `shmem_get`

A `const`-modified pointer argument to a function call always has a mode of IN.

I think that:
- Model 1 is what @min-si is suggesting we use here
- Model 2 captures something closer to the true nature, but is less informative
- Model 3 is what I think OpenSHMEM seems to use, except for its inconsistencies/errors

Of course, there are strange exceptions to these models. For example, the `dest` argument of `shmem_broadcast` will only be modified when the calling PE is not the root.

Right now, the night before the RCM draft cutoff, I'm not comfortable switching from Model 3 to Model 1. 

**Edit**:
~~I'll put together a new PR to fix the inconsistencies in OpenSHMEM's use of Model 3 and file an issue for broader discussion.~~
The specification actually looks pretty split between Model 1 and Model 3. I've raised https://github.com/openshmem-org/specification/issues/147 for broader consideration.

Tagging @BryantLam @davidozog for broader input.

**Comment by nspark** [comment]
@min-si I'm closing this as I've resolved the RMA/AMO Section issues with intents in 44ddd7d.

**Pull request closed without merging**
